spring:
  profiles:
    active: test #指定为测试环境

#数据库配置
  datasource:
    url: jdbc:mysql://192.168.2.5:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: false
      goods:
        url: jdbc:mysql://localhost:3306/demo_goods?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      member:
        url: jdbc:mysql://localhost:3306/demo_member?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      sss:
        url: jdbc:mysql://localhost:3306/demo_statistics?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      system:
        url: jdbc:mysql://localhost:3306/demo_system?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      trade:
        url: jdbc:mysql://localhost:3306/demo_trade?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      distribution:
        url: jdbc:mysql://localhost:3306/demo_distribution?useUnicode=true&characterEncoding=utf8&autoReconnect=true

#rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zhenghao
    password: zhenghao
    virtual-host: /

#elasticsearch配置
  data:
    elasticsearch:
      cluster-name: elasticsearch-cluster
      cluster-nodes: 192.168.2.12:9300,192.168.2.13:9300
      index-name: javashop

#redis 配置
redis:
  type: standalone
  config :
    type: manual
  host: localhost
  port: 6379
  password:
  maxIdle: 500
  maxTotal: 500
  maxWaitMillis: -1    


# 开发环境日志为debug      
logging:
  level:
    org.springframework: ERROR
    com.enation.app : DEBUG

#java 系统配置
#具体请参考：http://doc.javamall.com.cn/current/devlop/config-server.html
javashop:
  product: stand #定义系统标准产品，微服务指定为： microservice
  license[0]: abcde #license请向售后人员索要
  #token加密秘钥，请务必更换此词串，且注意保密
  token-secret: 85d6ce9da4e943ff4dcd367ab3d94164    
  timeout:
    accessTokenTimeout:  1200 #访问token失效时间 单位秒
    refreshTokenTimeout: 1800 #刷新token失效时间 单位秒
    captchaTimout:  120       #验证码失效时间 单位秒
    smscodeTimout: 120        #短信验证码失效时间 单位秒
  isDemoSite: no
  ssl: off #是否开启ssl
  domain:
    main: javamall.com.cn #请配置为您站点的主域名
    buyer: buyer.javamall.com.cn #配置为您买家端PC的域名
    mobileBuyer: m.buyer.javamall.com.cn  #配置为您买家端WAP的域名

xxl:
  job:
    admin:
      addresses:  http://192.168.2.5:8080/xxl-job-admin
    executor:
      appname: timing-job-execute 
      ip: 
      port: 6999
      logpath:  /opt/xxl-serverlogs
      logretentiondays: -1
    accessToken:


